# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('contactNo', models.IntegerField()),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('AC', 'Active')], default='PN', max_length=2)),
                ('key', models.CharField(max_length=5)),
                ('uniqueKey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
