# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20170526_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sessionID',
            field=models.CharField(max_length=40),
        ),
    ]
