# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20170527_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='uniqueKey',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
