# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20170527_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uniqueKey',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
