# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_auto_20170527_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(max_length=5),
        ),
    ]
